---
title: "Untitled"
author: "Richard D. Morey"
date: "14/11/2016"
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('settings.R')

df = as.integer( (nrow(m) - 1L) * (ncol(m) - 1L) )

contcor = contcor & (df==1)  
```


```{r echo=FALSE, warning=FALSE}
z = chisq.test(m, correct = contcor)

X2 = z$statistic
pval = z$p.value
```

### Computing the $p$ value

We report this as $X^2(`r df`) = `r round(X2, 3)`$.

```{r fig.width=6, fig.height=4, echo=FALSE}

do.call(par, par.list)
par(lwd=1)

if(pval > .01){
  maxp = .001
}else{
  maxp = .0005
}

if(df > 2){
  minp = 0
  maxy = dchisq(df-2, df)*1.1
}else if(df == 2){
  minp = 0
  maxy = dchisq(0,df)*1.1
}else{
  minp = .01
  maxy = dchisq(qchisq(.05, df),df)
}

xx = qchisq(seq(minp,1-maxp, len = 200), df = df)

yy = dchisq(xx, df = df)

plot(xx,yy, ty='l', axes=FALSE, ylab="Density", xlab = expression(X^2),ylim=c(0,maxy))
axis(1)
abline(v = X2, col=rgb(1,0,0,.5))
abline(v = 0)

text(X2,par()$usr[4], "Observed statistic", adj=c(1.1,1.1), srt=90,col=rgb(1,0,0,.5))

xx1 = c(xx[xx<X2], X2)
yy1 = dchisq(xx1, df = df)
polygon(c(xx1,rev(xx1)), c(yy1, yy1*0), col=rgb(0,0,1,.3), border=NA)

xx1 = c(X2, xx[xx>X2])
yy1 = dchisq(xx1, df = df)
polygon(c(xx1,rev(xx1)), c(yy1, yy1*0), col=rgb(1,0,0,.3), border=NA)


```

```{r fig.width=6, fig.height=4, echo=FALSE}

do.call(par, par.list)
par(lwd=1)

if(pval > .01){
  maxp = .001
}else{
  maxp = .0005
}

if(df > 1){
  minp = 0
}else{
  minp = .01
}


xx = qchisq(seq(minp,1-maxp, len = 200), df = df)

yy = pchisq(xx, df = df)

plot(xx,yy, ty='l', axes=FALSE, ylab=expression(paste("Probability of smaller ", X^2, " (1-p)")), xlab = expression(X^2), ylim=c(0,1))
axis(1)
axis(2)
abline(v = X2, col=rgb(1,0,0,.5))
#abline(v = 0)

text(X2,par()$usr[4], "Observed statistic", adj=c(1.1,1.1), srt=90,col=rgb(1,0,0,.5))

segments(-10, 1-pval, X2, 1-pval, col=rgb(1,0,0,.5))
points( X2, 1-pval, pch=19, col=rgb(1,0,0,.5))
#abline(h = 1-pval)

abline(h=1,col=rgb(0,0,0,.5))

```

We report this as $X^2(`r df`) = `r round(X2, 3)`, p = `r round(pval, 3)`$.

